export const IMAGE_CARD_CELL_MAX_HEIGHT = 800;
export const IMAGE_CARD_CELL_WIDTH = 400;
export const IMAGE_BOARD_CONTAINER_HEIGHT = 1000;
export const IMAGE_BOARD_CONTAINER_WIDTH = 1250;
export const IMAGE_BOARD_CONTAINER_SPACER = 5;
export const IMAGE_BOARD_COLUMN_MAX_COUNT = 3;

export const HEADER_HEIGHT = 20;
